//! SQL query functions for settings and theme CRUD (US5).
//! All functions are ssr-only. Uses parameterized SQL with static string literals.
//! Secret-bearing settings (weather API key, OIDC client secret) are encrypted at rest
//! using an XOR-based stream cipher with HMAC-SHA256 as the PRF, keyed from the server secret.
//! Secrets are never returned to non-admins or logged.

#![cfg(feature = "ssr")]

use std::str::FromStr;

use base64::prelude::*;
use chrono::Utc;
use getrandom::fill;
use hmac::{Hmac, Mac};
use sha2::Sha256;
use sqlx::{Row, SqlitePool};
use uuid::Uuid;

use crate::domain::{
    AuthSettings, DesignTokens, IntegrationSettings, SearchProviderConfig, SettingsPatch,
    SettingsView, Theme, ThemeInput, ThemeSummary, WeatherSettings,
};
use crate::error::AppError;

type HmacSha256 = Hmac<Sha256>;

// --- Encryption at rest for secret-bearing settings ---

/// Keys whose values are secret-bearing and must be encrypted at rest.
const SECRET_KEYS: &[&str] = &["weather", "auth"];

/// Encrypt a plaintext string using an XOR keystream derived from HMAC-SHA256.
/// Returns a base64-encoded blob: `nonce_b64 || ciphertext`.
/// The nonce is 16 random bytes; the keystream is generated by HMAC(key, nonce || counter).
fn encrypt_secret(server_key: &[u8], plaintext: &str) -> Result<String, AppError> {
    let mut nonce = [0u8; 16];
    fill(&mut nonce).map_err(|_| AppError::Internal)?;
    let plaintext_bytes = plaintext.as_bytes();

    let mut ciphertext = Vec::with_capacity(plaintext_bytes.len());
    let mut counter: u32 = 0;
    let mut offset = 0;

    while offset < plaintext_bytes.len() {
        let mut mac = HmacSha256::new_from_slice(server_key).map_err(|_| AppError::Internal)?;
        mac.update(&nonce);
        mac.update(&counter.to_le_bytes());
        let block = mac.finalize().into_bytes();
        let block_len = block.len().min(plaintext_bytes.len() - offset);
        for i in 0..block_len {
            ciphertext.push(plaintext_bytes[offset + i] ^ block[i]);
        }
        offset += block_len;
        counter += 1;
    }

    let mut blob = Vec::with_capacity(nonce.len() + ciphertext.len());
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);
    Ok(BASE64_STANDARD.encode(&blob))
}

/// Decrypt a base64-encoded blob produced by `encrypt_secret`.
fn decrypt_secret(server_key: &[u8], encoded: &str) -> Result<String, AppError> {
    let blob = BASE64_STANDARD
        .decode(encoded)
        .map_err(|_| AppError::Internal)?;
    if blob.len() < 16 {
        return Err(AppError::Internal);
    }
    let nonce = &blob[..16];
    let ciphertext = &blob[16..];

    let mut plaintext = Vec::with_capacity(ciphertext.len());
    let mut counter: u32 = 0;
    let mut offset = 0;

    while offset < ciphertext.len() {
        let mut mac = HmacSha256::new_from_slice(server_key).map_err(|_| AppError::Internal)?;
        mac.update(nonce);
        mac.update(&counter.to_le_bytes());
        let block = mac.finalize().into_bytes();
        let block_len = block.len().min(ciphertext.len() - offset);
        for i in 0..block_len {
            plaintext.push(ciphertext[offset + i] ^ block[i]);
        }
        offset += block_len;
        counter += 1;
    }

    String::from_utf8(plaintext).map_err(|_| AppError::Internal)
}

/// Check if a setting key is secret-bearing.
fn is_secret_key(key: &str) -> bool {
    SECRET_KEYS.iter().any(|sk| key.starts_with(sk))
}

// --- Typed settings registry ---

/// Setting keys in the typed registry.
pub mod keys {
    pub const SEARCH_PROVIDERS: &str = "search.providers";
    pub const SEARCH_DEFAULT: &str = "search.default";
    pub const INTEGRATIONS: &str = "integrations";
    pub const WEATHER: &str = "weather";
    pub const THEME_ACTIVE: &str = "theme.active";
    pub const AUTH: &str = "auth";
}

/// Read a raw setting value as JSON string.
pub async fn get_setting_raw(pool: &SqlitePool, key: &str) -> Result<Option<String>, AppError> {
    let row: Option<(String,)> = sqlx::query_as("SELECT value FROM setting WHERE key = ?")
        .bind(key)
        .fetch_optional(pool)
        .await?;
    Ok(row.map(|(v,)| v))
}

/// Write a raw setting value (upsert).
pub async fn set_setting_raw(
    pool: &SqlitePool,
    key: &str,
    value: &str,
    server_key: &[u8],
) -> Result<(), AppError> {
    let now = Utc::now().to_rfc3339();
    let stored = if is_secret_key(key) && !server_key.is_empty() {
        encrypt_secret(server_key, value)?
    } else {
        value.to_string()
    };

    sqlx::query(
        "INSERT INTO setting (key, value, updated_at) VALUES (?, ?, ?) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at",
    )
    .bind(key)
    .bind(&stored)
    .bind(&now)
    .execute(pool)
    .await?;
    Ok(())
}

/// Read a setting value, decrypting if secret-bearing.
pub async fn get_setting_decrypted(
    pool: &SqlitePool,
    key: &str,
    server_key: &[u8],
) -> Result<Option<String>, AppError> {
    let raw = get_setting_raw(pool, key).await?;
    match raw {
        Some(v) => {
            if is_secret_key(key) && !server_key.is_empty() {
                decrypt_secret(server_key, &v).map(Some)
            } else {
                Ok(Some(v))
            }
        }
        None => Ok(None),
    }
}

// --- Settings view (typed) ---

/// Read all settings into a typed SettingsView.
/// If `include_secrets` is false, secret-bearing fields are set to None.
pub async fn get_settings_view(
    pool: &SqlitePool,
    server_key: &[u8],
    include_secrets: bool,
) -> Result<SettingsView, AppError> {
    let search_providers = get_search_providers_typed(pool).await?;
    let integrations = get_integrations_typed(pool).await?;
    let weather = get_weather_typed(pool, server_key, include_secrets).await?;
    let auth = get_auth_typed(pool, server_key, include_secrets).await?;
    let theme_active = get_setting_raw(pool, keys::THEME_ACTIVE).await?;

    Ok(SettingsView {
        search_providers,
        integrations,
        weather,
        auth,
        theme_active,
    })
}

/// Apply a settings patch, persisting each section.
pub async fn apply_settings_patch(
    pool: &SqlitePool,
    patch: &SettingsPatch,
    server_key: &[u8],
) -> Result<(), AppError> {
    if let Some(ref sp) = patch.search_providers {
        set_setting_raw(
            pool,
            keys::SEARCH_PROVIDERS,
            &serde_json::to_string(sp).unwrap_or_default(),
            server_key,
        )
        .await?;
    }
    if let Some(ref integ) = patch.integrations {
        set_setting_raw(
            pool,
            keys::INTEGRATIONS,
            &serde_json::to_string(integ).unwrap_or_default(),
            server_key,
        )
        .await?;
    }
    if let Some(ref weather) = patch.weather {
        set_setting_raw(
            pool,
            keys::WEATHER,
            &serde_json::to_string(weather).unwrap_or_default(),
            server_key,
        )
        .await?;
    }
    if let Some(ref auth) = patch.auth {
        set_setting_raw(
            pool,
            keys::AUTH,
            &serde_json::to_string(auth).unwrap_or_default(),
            server_key,
        )
        .await?;
    }
    if let Some(ref theme_active) = patch.theme_active {
        match theme_active {
            Some(id) => {
                set_setting_raw(pool, keys::THEME_ACTIVE, id, server_key).await?;
            }
            None => {
                sqlx::query("DELETE FROM setting WHERE key = ?")
                    .bind(keys::THEME_ACTIVE)
                    .execute(pool)
                    .await?;
            }
        }
    }
    Ok(())
}

// --- Typed section readers ---

async fn get_search_providers_typed(pool: &SqlitePool) -> Result<SearchProviderConfig, AppError> {
    let raw = get_setting_raw(pool, keys::SEARCH_PROVIDERS).await?;
    Ok(match raw {
        Some(json) => serde_json::from_str(&json).unwrap_or_default(),
        None => SearchProviderConfig::default(),
    })
}

pub async fn get_integrations_typed(pool: &SqlitePool) -> Result<IntegrationSettings, AppError> {
    let raw = get_setting_raw(pool, keys::INTEGRATIONS).await?;
    Ok(match raw {
        Some(json) => serde_json::from_str(&json).unwrap_or_default(),
        None => IntegrationSettings::default(),
    })
}

pub async fn get_weather_typed(
    pool: &SqlitePool,
    server_key: &[u8],
    include_secrets: bool,
) -> Result<WeatherSettings, AppError> {
    let raw = get_setting_decrypted(pool, keys::WEATHER, server_key).await?;
    Ok(match raw {
        Some(json) => {
            let mut ws: WeatherSettings = serde_json::from_str(&json).unwrap_or_default();
            if !include_secrets {
                ws.api_key = None;
            }
            ws
        }
        None => WeatherSettings::default(),
    })
}

async fn get_auth_typed(
    pool: &SqlitePool,
    server_key: &[u8],
    include_secrets: bool,
) -> Result<AuthSettings, AppError> {
    let raw = get_setting_decrypted(pool, keys::AUTH, server_key).await?;
    Ok(match raw {
        Some(json) => {
            let mut aset: AuthSettings = serde_json::from_str(&json).unwrap_or_default();
            if !include_secrets {
                aset.oidc_client_secret = None;
            }
            aset
        }
        None => AuthSettings::default(),
    })
}

// --- Theme CRUD ---

fn row_to_theme(row: &sqlx::sqlite::SqliteRow) -> Theme {
    let tokens_json: String = row.get("tokens");
    let tokens: DesignTokens = serde_json::from_str(&tokens_json).unwrap_or_default();
    Theme {
        id: Uuid::from_str(row.get::<String, _>("id").as_str()).unwrap_or_default(),
        name: row.get("name"),
        tokens,
        custom_css: row.get("custom_css"),
        is_builtin: row.get::<i64, _>("is_builtin") != 0,
        created_by: row
            .get::<Option<String>, _>("created_by")
            .map(|s| Uuid::from_str(&s).unwrap_or_default()),
        created_at: row.get("created_at"),
    }
}

fn row_to_theme_summary(row: &sqlx::sqlite::SqliteRow) -> ThemeSummary {
    ThemeSummary {
        id: Uuid::from_str(row.get::<String, _>("id").as_str()).unwrap_or_default(),
        name: row.get("name"),
        is_builtin: row.get::<i64, _>("is_builtin") != 0,
        created_at: row.get("created_at"),
    }
}

/// List all themes (summaries only — no tokens/CSS).
pub async fn list_themes_query(pool: &SqlitePool) -> Result<Vec<ThemeSummary>, AppError> {
    let rows = sqlx::query(
        "SELECT id, name, is_builtin, created_at FROM theme ORDER BY is_builtin DESC, created_at ASC",
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.iter().map(row_to_theme_summary).collect())
}

/// Get a theme by id (full tokens + CSS).
pub async fn get_theme_by_id(pool: &SqlitePool, id: Uuid) -> Result<Theme, AppError> {
    let row = sqlx::query(
        "SELECT id, name, tokens, custom_css, is_builtin, created_by, created_at \
         FROM theme WHERE id = ?",
    )
    .bind(id.to_string())
    .fetch_optional(pool)
    .await?;

    match row {
        Some(r) => Ok(row_to_theme(&r)),
        None => Err(AppError::NotFound),
    }
}

/// Get the active theme (full tokens + CSS). Returns None if no active theme is set.
pub async fn get_active_theme_query(pool: &SqlitePool) -> Result<Option<Theme>, AppError> {
    let active_id = get_setting_raw(pool, keys::THEME_ACTIVE).await?;
    match active_id {
        Some(id_str) => {
            let id = Uuid::from_str(&id_str).unwrap_or_default();
            let theme = get_theme_by_id(pool, id).await?;
            Ok(Some(theme))
        }
        None => Ok(None),
    }
}

/// Save a new theme (create). Returns the created theme with id.
pub async fn save_theme_query(
    pool: &SqlitePool,
    input: &ThemeInput,
    created_by: Option<Uuid>,
) -> Result<Theme, AppError> {
    if input.name.trim().is_empty() {
        return Err(AppError::Validation("theme name must not be empty".into()));
    }
    if input.name.len() > 128 {
        return Err(AppError::Validation(
            "theme name must be at most 128 characters".into(),
        ));
    }

    let id = Uuid::now_v7();
    let now = Utc::now().to_rfc3339();
    let tokens_json = serde_json::to_string(&input.tokens).unwrap_or_else(|_| "{}".to_string());
    let created_by_str = created_by.map(|u| u.to_string());

    sqlx::query(
        "INSERT INTO theme (id, name, tokens, custom_css, is_builtin, created_by, created_at) \
         VALUES (?, ?, ?, ?, 0, ?, ?)",
    )
    .bind(id.to_string())
    .bind(&input.name)
    .bind(&tokens_json)
    .bind(&input.custom_css)
    .bind(&created_by_str)
    .bind(&now)
    .execute(pool)
    .await?;

    get_theme_by_id(pool, id).await
}

/// Set the active theme by id.
pub async fn set_active_theme_query(
    pool: &SqlitePool,
    id: Uuid,
    server_key: &[u8],
) -> Result<(), AppError> {
    // Verify theme exists
    let _ = get_theme_by_id(pool, id).await?;
    set_setting_raw(pool, keys::THEME_ACTIVE, &id.to_string(), server_key).await?;
    Ok(())
}

// --- Built-in theme seeding ---

/// Seed built-in themes if none exist.
pub async fn seed_builtin_themes(pool: &SqlitePool) -> Result<(), AppError> {
    let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM theme WHERE is_builtin = 1")
        .fetch_one(pool)
        .await?;

    if count.0 > 0 {
        return Ok(());
    }

    let now = Utc::now().to_rfc3339();

    // Light theme
    let light_tokens = DesignTokens {
        bg: Some("#ffffff".into()),
        surface: Some("#f5f5f5".into()),
        text: Some("#1a1a1a".into()),
        text_muted: Some("#6b7280".into()),
        accent: Some("#3b82f6".into()),
        accent_text: Some("#ffffff".into()),
        border: Some("#e5e7eb".into()),
        radius: Some("8px".into()),
        spacing: Some("16px".into()),
        font: Some("system-ui, sans-serif".into()),
        mode: Some("light".into()),
    };
    let light_id = Uuid::now_v7();
    sqlx::query(
        "INSERT INTO theme (id, name, tokens, custom_css, is_builtin, created_by, created_at) \
         VALUES (?, 'Light', ?, NULL, 1, NULL, ?)",
    )
    .bind(light_id.to_string())
    .bind(serde_json::to_string(&light_tokens).unwrap_or_default())
    .bind(&now)
    .execute(pool)
    .await?;

    // Dark theme
    let dark_tokens = DesignTokens {
        bg: Some("#1a1a2e".into()),
        surface: Some("#16213e".into()),
        text: Some("#e2e8f0".into()),
        text_muted: Some("#94a3b8".into()),
        accent: Some("#3b82f6".into()),
        accent_text: Some("#ffffff".into()),
        border: Some("#334155".into()),
        radius: Some("8px".into()),
        spacing: Some("16px".into()),
        font: Some("system-ui, sans-serif".into()),
        mode: Some("dark".into()),
    };
    let dark_id = Uuid::now_v7();
    sqlx::query(
        "INSERT INTO theme (id, name, tokens, custom_css, is_builtin, created_by, created_at) \
         VALUES (?, 'Dark', ?, NULL, 1, NULL, ?)",
    )
    .bind(dark_id.to_string())
    .bind(serde_json::to_string(&dark_tokens).unwrap_or_default())
    .bind(&now)
    .execute(pool)
    .await?;

    Ok(())
}

// --- Tests for encryption round-trip ---

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let key = b"test-server-key-1234567890123456";
        let plaintext = "my-secret-api-key-12345";
        let encrypted = encrypt_secret(key, plaintext).expect("encrypt");
        assert_ne!(
            encrypted, plaintext,
            "ciphertext should differ from plaintext"
        );
        let decrypted = decrypt_secret(key, &encrypted).expect("decrypt");
        assert_eq!(decrypted, plaintext, "round-trip should preserve plaintext");
    }

    #[test]
    fn test_encrypt_decrypt_empty() {
        let key = b"test-server-key";
        let plaintext = "";
        let encrypted = encrypt_secret(key, plaintext).expect("encrypt");
        let decrypted = decrypt_secret(key, &encrypted).expect("decrypt");
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_encrypt_decrypt_long() {
        let key = b"test-server-key";
        let plaintext = "x".repeat(1000);
        let encrypted = encrypt_secret(key, &plaintext).expect("encrypt");
        let decrypted = decrypt_secret(key, &encrypted).expect("decrypt");
        assert_eq!(decrypted, plaintext);
    }
}
